<?php

require_once dirname(__FILE__) . '/../../../src/Browser/Mozilla.php';

/**
 * Test class for Browser_Mozilla.
 * Generated by PHPUnit on 2011-09-03 at 00:49:42.
 */
class Browser_MozillaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Browser_Mozilla
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Browser_Mozilla;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Browser_Mozilla::borderRadius
     * @dataProvider borderRadiusProvider
     */
    public function testBorderRadius($cssString, $mozValue)
    {
        $cssString = $this->object->borderRadius($cssString);
        $this->assertContains($mozValue, $cssString);
    }
    
    public function borderRadiusProvider()
    {
        $strings = array(
            array("p {border-radius: 5px;}",             "-moz-border-radius: 5px;"),
            array("p {border-radius: 5px}",              "-moz-border-radius: 5px;"),
            array("p {border-top-right-radius: 5px}",    "-moz-border-radius-topright: 5px;"),
            array("p {border-top-left-radius: 5px}",     "-moz-border-radius-topleft: 5px;"),
            array("p {border-bottom-right-radius: 5px}", "-moz-border-radius-bottomright: 5px;"),
            array("p {border-bottom-left-radius: 5px}",  "-moz-border-radius-bottomleft: 5px;"),
        );
        return $strings;
    }
}