<?php

require_once dirname(__FILE__) . '/../../../src/Browser/Explorer.php';

/**
 * Test class for Browser_Explorer.
 * Generated by PHPUnit on 2011-09-06 at 23:10:14.
 */
class Browser_ExplorerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Browser_Explorer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Browser_Explorer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
