<?php

require_once dirname(__FILE__) . '/../../../src/Browser/Webkit.php';

/**
 * Test class for Browser_Webkit.
 * Generated by PHPUnit on 2011-09-06 at 23:10:15.
 */
class Browser_WebkitTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Browser_Webkit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Browser_Webkit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
