<?php
require_once dirname(__FILE__) . '/../BaseTest.php';
require_once dirname(__FILE__) . '/../../../src/Browser/Konqueror.php';

/**
 * Test class for Browser_Konqueror.
 * Generated by PHPUnit on 2011-09-06 at 23:10:16.
 */
class Browser_KonquerorTest extends BaseTest {

    /**
     * @var Browser_Konqueror
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Browser_Konqueror;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
}