<?php
require_once dirname(__FILE__) . '/BaseTest.php';
require_once dirname(__FILE__) . '/../../src/Browser.php';

/**
 * Test class for Browser.
 * Generated by PHPUnit on 2011-09-03 at 00:49:41.
 */
class BrowserTest extends BaseTest {

    /**
     * @var Browser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Browser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
}