<?php

require_once dirname(__FILE__) . '/../../src/CssAlly.php';

/**
 * Test class for CssAlly.
 * Generated by PHPUnit on 2011-09-03 at 00:15:08.
 */
class CssAllyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CssPrefixer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CssAlly;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CssPrefixer::getBrowser
     * @dataProvider getBrowserProvider
     * @param type $browser 
     */
    public function testGetBrowser($browser)
    {
        
    }
    
    public function getBrowserProvider()
    {
        return array();
    }
    
    /**
     * @covers CssPrefixer::setBrowser
     * @depends testGetBrowser
     * @param type $browser
     * @param type $generate 
     */
    public function testSetBrowser($browser, $generate)
    {
        
    }
    
    /**
     * @covers CssPrefixer::setBrowsers
     * @depends testSetBrowser
     * @param array $browsers 
     */
    public function testSetMultipleBrowsers(array $browsers)
    {
        
    }
}